### ISSUE TITLE
Error processing latest 36.331 e80 spec

### ISSUE THREAD

**Issue by rgyger** [intrig/xenon#16] opened 2019-04-24 17:26 UTC
I'm trying to update the 36.331 asn doc to e80. 

Steps performed:
1) export 36.331.doc rev e80 as text using MS Word
2) run asnstrip on the text and save as 36.331-e80.asn
3) remove all "-- ASN1STOP" and "-- ASN1START" blocks from asn file
4) update CMakeLists.txt file and rerun build. 

The build is failing with the following error. The line 4253 comment was added by modifying asnast.h to output the error string to cerr before calling IT_PANIC()

[ 15%] Generating src/xenon/xddl/3GPP/TS-36.331.xddl
opening src/xenon/xddl/asn/36.331/36.331-e80.asn
finished module EUTRA-RRC-Definitions
finished module PC5-RRC-Definitions
finished module NBIOT-RRC-Definitions
finished module EUTRA-UE-Variables
finished module NBIOT-UE-Variables
finished module EUTRA-Sidelink-Preconf
finished module EUTRA-InterNodeDefinitions
finished module NBIOT-InterNodeDefinitions
parsing complete
writing xddl
line 4253: undefined instance for type 11BooleanType
src/xenon/xddl/asn/36.331/36.331-e80.asn: [src/xenon/tools/asnx/asnast.h:137]
make[2]: *** [src/xenon/xddl/3GPP/TS-36.331.xddl] Error 1
make[1]: *** [xenon/xddl/3GPP/36.331/CMakeFiles/36_331.dir/all] Error 2
make: *** [all] Error 2

**Comment by rgyger** [comment] 2019-04-30 14:03
Looks like it's something introduced in rev 13 of the 36.331 spec.

Up to rev 12 passes. rev 13 fails with the 11BooleanType error.

**Comment by wythe** [comment] 2019-05-06 14:02
@rgyger could you make a branch with your above change and push it to github and give me a link?  I'm really a bit busy atm.

**Comment by rgyger** [comment] 2019-05-06 15:07
The only change is to add the following above line 136 of asnast.h:

        std::cerr << os.str() << std::endl;

I added it because IT_PANIC wasn't giving any info,

**Comment by wythe** [comment] 2019-05-06 15:28
I'm talking about the updated xddl files you made from rev 13.

**Comment by rgyger** [comment] 2019-05-06 17:04
no access?

**Comment by wythe** [comment] 2019-05-06 17:41
You have to fork the xenon repo on github, clone it, add the updated files, and then push back to github.  Then I can download it. 

Here's the basic process:
https://help.github.com/en/articles/fork-a-repo

**Comment by rgyger** [comment] 2019-05-06 19:25
Ok. I’ve forked it and pushed the updated 36.331 asn file.

It’s under rgyger/xenon

**Comment by wythe** [comment] 2019-05-06 21:20
Ok thanks, I reproduced the error.  Looking at it now.

**Comment by wythe** [comment] 2019-05-12 16:21
@rgyger, I have this bug fixed and the r13 file upgraded on my personal fork (master).  Please give it a shot:
https://github.com/wythe/xenon.git

The intrig/xenon tree seems to be a bit behind.  I made some updates a few years ago and didn't get them merged. So my @wythe tree is more accurate for now.  I will update the intrig tree on my own time and let you know.

**Comment by rgyger** [comment] 2019-05-12 23:13
Thanks. I’ll check it out.

**Comment by rgyger** [comment] 2019-05-15 20:19
It’s working great. I even updated to the latest r14 spec and it’s working
fine.

Thanks much.

**Comment by wythe** [comment] 2019-07-06 13:15
Fixed in #17.

Richard, you can can go back to using intrig/xenon as the upstream.  I'll be making some additional improvements.  You can see what I've done so far by looking at the closed Pull Requests.

If you like, you can submit a PR to get r14 into the master. Here is a nice guide if you are new to this process:  https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Closed by wythe** 2019-07-06 13:15 UTC
Labels: bug

**Comment by rgyger** [comment] 2019-07-06 13:57
Thanks.

We’re actually looking at running with r15 now to get the 5g messaging.

On first run thru the compile it failed. I’ll know more when I another
chance to look at it.

**Comment by wythe** [comment] 2019-07-06 14:27
Ok great. I'll stay tuned. On Jul 6, 2019 8:57 AM, rgyger <notifications@github.com> wrote:Thanks.



We’re actually looking at running with r15 now to get the 5g messaging.



On first run thru the compile it failed. I’ll know more when I another

chance to look at it.



On Sat, Jul 6, 2019 at 8:15 AM Mark Beckwith <notifications@github.com>

wrote:
